### ISSUE TITLE
GeForce GTX 860M Dedicated Graphics for Laptops

### ISSUE THREAD

**Issue by XelaPy** [bitsawer/renpy-shader#1]
- Everything works perfectly except for "windy" image distortions. A solid black image is shown instead. The card should have modern OpenGL support as it runs Skyrim/GTA5/N4S and a lot of other games at good fps without any issues, maybe some OpenGL setting need to be on override for Ren'Py in Driver Settings but I would not know what that may be...

OS is Win 8.1, all drivers/Ren'Py updated.

Everything works perfectly fine on Desktop (same OS and the exact same Ren'Py shared through DropBox, just different hardware).

And this looks amazing! Great job!

**Comment by bitsawer** [comment]
I simplified the wind effect pixel shader in commit a43d31e815e34ad2493cd3b830757f43eb7ada5b which might or might not help with this. It was pretty unoptimized (and still is), but the operation count might now be small enough for it to work on older devices. Especially if other effects (like blur and "beam me up") work.

If it still doesn't work there is still some room for more optimizations.

**Comment by XelaPy** [comment]
I thought that I triple-checked before reporting the error but onboard gpu was used. After forcing dedicated card, everything runs just as perfect as on the desktop.
